services:
  db:
    networks:
      - nestjs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  backend:
    networks:
      - nestjs-network
    depends_on:
      db:
        condition: service_healthy
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

networks:
  nestjs-network:

volumes:
  pgdata:
  pgadmin-data:
